import { rm } from "node:fs/promises"
import path from "node:path"

const output = path.join("/tmp", `opencode-ensemble-dashboard-${process.pid}.css`)
const target = path.join(process.cwd(), "src", "dashboard-css.generated.ts")

try {
  const process = Bun.spawn([
    "bunx",
    "tailwindcss",
    "--config",
    "tailwind.config.cjs",
    "--input",
    "dashboard-tailwind.css",
    "--output",
    output,
    "--minify",
  ], { stderr: "pipe" })
  const [exitCode, stderr] = await Promise.all([process.exited, new Response(process.stderr).text()])
  if (exitCode !== 0) throw new Error(`Tailwind failed (${exitCode}): ${stderr}`)

  const css = await Bun.file(output).text()
  await Bun.write(target, `/** Generated by generate-dashboard-css.ts. Do not edit. */\nexport const DASHBOARD_CSS = ${JSON.stringify(css)}\n`)
} finally {
  await rm(output, { force: true })
}
